import Head from 'next/head';
import { connectToDatabase } from '../libs/mongodb';
import { Ruleta_abismo } from '../components';

export default function Home({ bans, part }) {
	return (
		<>
			<Head>
				<title>Roulette</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='absolute w-full h-full bg-slate-800'></div>
			<div className=''>
				<div>
					<div className='w-full'></div>
				</div>
			</div>
		</>
	);
}

export async function getServerSideProps() {
	const { db } = await connectToDatabase();

	const data = await db
		.collection('abyss_datatable')
		.find({})
		.limit(20)
		.toArray();

	const bansjson = JSON.parse(JSON.stringify(data[0].bans));
	const partjson = JSON.parse(JSON.stringify(data[0].part));

	return {
		props: {
			bans: bansjson,
			part: partjson,
		},
	};
}
