import Head from 'next/head';
import { connectToDatabase } from '../libs/mongodb';
import { Ruleta_abismo, SingleRoll } from '../components';

export default function Home({ bans, part }) {
	return (
		<>
			<Head>
				<title>Roulette</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='absolute w-full h-full bg-slate-800 -z-50'>
				<div className='z-30'>
					<div className='my-10 py-10 text-center w-full'>
						<div className='float-left w-[60%]'>
							<div className='border-8 p-8 lg:px-16 rounded-xl align-middle inline-block lg:mx-8 w-[30%]'>
								<div className='border-4 block'>a</div>
								<div className='border-4 block'>a</div>
								<div className='border-4 block'>a</div>
								<div className='border-4 block'>a</div>
							</div>
							<div className='border-8 rounded-xl align-middle inline-block lg:mx-8 w-[40%]'>
								<SingleRoll list={bans} />
							</div>
						</div>
						<div className='float-right w-[40%]'>
							<div className='border-8 p-8 lg:px-16 rounded-xl align-middle inline-block lg:mx-8'>
								a
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}

export async function getServerSideProps() {
	const { db } = await connectToDatabase();

	const data = await db
		.collection('abyss_datatable')
		.find({})
		.limit(20)
		.toArray();

	const bansjson = JSON.parse(JSON.stringify(data[0].bans));
	const partjson = JSON.parse(JSON.stringify(data[0].part));

	return {
		props: {
			bans: bansjson,
			part: partjson,
		},
	};
}
